Inzynierka/force-app/main/default/objects/Ranking__c/Ranking__c.object-meta.xml
<CustomObject>
    <label>Ranking</label>
    <nameField>
        <label>Ranking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ranking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rankings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ranking_has_user__c/Ranking_has_user__c.object-meta.xml
<CustomObject>
    <label>Ranking has user</label>
    <nameField>
        <label>Ranking has user Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ranking has users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ranking_has_user__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Ranking</label>
    <referenceTo>Ranking__c</referenceTo>
    <relationshipLabel>Ranking has users</relationshipLabel>
    <relationshipName>Ranking_has_users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ranking_has_user__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ranking_has_users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Goal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rapid weight loss (~1kg per week)
                    </fullName>
                <label>Rapid weight loss</label>
            </value>
            <value>
                <fullName>Quick weight loss (~0.75kg per week)</fullName>
                <label>Quick weight loss</label>
            </value>
            <value>
                <fullName>Moderate weight loss (~0.5kg per week)
                    </fullName>
                <label>Moderate weight loss</label>
            </value>
            <value>
                <fullName>Slow weight loss (~0.25kg per week)
                    </fullName>
                <label>Slow weight loss</label>
            </value>
            <value>
                <fullName>Keeping weight</fullName>
            </value>
            <value>
                <fullName>Rapid weight gain (~1kg per week)
                    </fullName>
                <label>Rapid weight gain</label>
            </value>
            <value>
                <fullName>Quick weight gain (~0.75kg per week)</fullName>
                <label>Quick weight gain</label>
            </value>
            <value>
                <fullName>Moderate weight gain (~0.5kg per week)
                    </fullName>
                <label>Moderate weight gain</label>
            </value>
            <value>
                <fullName>Slow weight gain (~0.25kg per week)
                    </fullName>
                <label>Slow weight gain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/PAL__c.field-meta.xml
<CustomField>
    <fullName>PAL__c</fullName>
    <label>PAL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lying in bed</fullName>
            </value>
            <value>
                <fullName>Low physical activity</fullName>
            </value>
            <value>
                <fullName>Moderate physical activity</fullName>
            </value>
            <value>
                <fullName>Regular exercise 2-3 times a week</fullName>
            </value>
            <value>
                <fullName>Daily exercises</fullName>
            </value>
            <value>
                <fullName>Professional athlete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestGetRanking.cls
@isTest
public with sharing class TestGetRanking {
    @TestSetup
    static void makeData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'fsd', Email='standard@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Test2', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='xdd@xdd.com');
        u.Gender__c = 'Male';
        u.Weight__c = 86.5;
        u.Height__c = 181;
        u.PAL__c = 'Moderate physical activity';
        u.Goal__c = 'Keeping weight';
        insert u;
        Ranking__c rank = new Ranking__c();
        rank.Name = 'Ranking #1';
        rank.Start_date__c = Date.today();
        rank.End_date__c = Date.today().addDays(7);
        insert rank;
        Ranking_has_user__c userInRank = new Ranking_has_user__c();
        userInRank.User__c = u.Id;
        userInRank.Ranking__c = rank.Id;
        insert userInRank;
    }
    @isTest
    static void getRankingTest(){
        
    }
}