Inzynierka/force-app/main/default/objects/Descriptor__c/Descriptor__c.object-meta.xml
<CustomObject>
    <label>Descriptor</label>
    <nameField>
        <label>Descriptor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descriptors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_Type__c/Meal_Type__c.object-meta.xml
<CustomObject>
    <label>Meal Type</label>
    <nameField>
        <label>MealType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MealTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/Descriptor__c.field-meta.xml
<CustomField>
    <fullName>Descriptor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Descriptor</label>
    <referenceTo>Descriptor__c</referenceTo>
    <relationshipLabel>MealTypes</relationshipLabel>
    <relationshipName>MealTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_type_has_product__c/Meal_type_has_product__c.object-meta.xml
<CustomObject>
    <label>Meal type has product</label>
    <nameField>
        <label>Meal type has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_type_has_product__c/fields/Grammage__c.field-meta.xml
<CustomField>
    <fullName>Grammage__c</fullName>
    <label>Grammage</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_type_has_product__c/fields/Meal_Type__c.field-meta.xml
<CustomField>
    <fullName>Meal_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meal Type</label>
    <referenceTo>Meal_Type__c</referenceTo>
    <relationshipLabel>MealTypeHasProducts</relationshipLabel>
    <relationshipName>MealTypeHasProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_type_has_product__c/fields/New_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Product</label>
    <referenceTo>New_Product__c</referenceTo>
    <relationshipLabel>MealTypeHasProducts</relationshipLabel>
    <relationshipName>MealTypeHasProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/New_Product__c/New_Product__c.object-meta.xml
<CustomObject>
    <label>New Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Calories__c.field-meta.xml
<CustomField>
    <fullName>Calories__c</fullName>
    <label>Calories</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Carbohydrates__c</fullName>
    <label>Carbohydrates</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Fat__c.field-meta.xml
<CustomField>
    <fullName>Fat__c</fullName>
    <label>Fat</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/classes/getMenusToFlow.cls
public with sharing class getMenusToFlow {
    public class FlowInput{
        @InvocableVariable public List<Meal_type__c> mealType;
    }

    @InvocableMethod(label='Get Menu By Flow Variables')
    public static FlowOutput[] products(List<FlowInput> params){
        FlowOutput[] results = new List<FlowOutput>();
        Set<Id> mealTypes = new Set<Id>();
        for(FlowInput input : params){
            for(Meal_type__c meal : input.mealType){
                mealTypes.add(meal.Id);
            }
        }

        List<Meal_type_has_product__c> breakfasts = [SELECT Id, Name, Meal_Type__c, New_Product__c, Grammage__c FROM Meal_type_has_product__c WHERE Meal_Type__c IN: mealTypes AND Meal_Type__r.Descriptor__r.Name = 'Breakfast'];
        Map<Id, Decimal> breakfastProductsGrammage = new Map<Id, Decimal>();
        for(Meal_type_has_product__c breakfast : breakfasts){
            breakfastProductsGrammage.put(breakfast.New_Product__c, breakfast.Grammage__c);
        }
        Map<Id, New_Product__c> breakfastProducts = new Map<Id, New_Product__c>([SELECT Name, Calories__c, Carbohydrates__c, Fat__c, Protein__c FROM New_Product__c WHERE Id IN: breakfastProductsGrammage.keySet()]);
        Map<String, List<Decimal>> breakfastOutput = new Map<String, List<Decimal>>();
        List<Product> products = new List<Product>();
        for(Id id : breakfastProductsGrammage.keySet()){
            List<Decimal> macros = new List<Decimal>();
            New_Product__c prod = breakfastProducts.get(id);
            Decimal grammage = breakfastProductsGrammage.get(id)/100;
            macros.add(prod.Calories__c*grammage);
            macros.add(prod.Protein__c*grammage);
            macros.add(prod.Fat__c*grammage);
            macros.add(prod.Carbohydrates__c*grammage);
            breakfastOutput.put(prod.Name, macros);
            Product product = new Product(prod.Name, prod.Calories__c*grammage, prod.Protein__c*grammage,
            prod.Fat__c*grammage, prod.Carbohydrates__c*grammage);
            products.add(product);
        }
        system.debug(products);
        results.add(new FlowOutput(products));

        return results;
    }
    
    public class FlowOutput{
        @InvocableVariable public List<Product> mealTypeProductOutput;

        public FlowOutput(List<Product> mealProduct) {
            this.mealTypeProductOutput = mealProduct;
        }
    }
    public class Product{
        @InvocableVariable public String name;
        @InvocableVariable public Decimal calories;
        @InvocableVariable public Decimal protein;
        @InvocableVariable public Decimal fat;
        @InvocableVariable public Decimal carbohydrates;

        public Product(String name, Decimal cal, Decimal prot, Decimal fat, Decimal carbo){
            this.name = name;
            this.calories = cal;
            this.protein = prot;
            this.fat = fat;
            this.carbohydrates = carbo;
        }
    }
}