Inzynierka/force-app/main/default/objects/Descriptor__c/Descriptor__c.object-meta.xml
<CustomObject>
    <label>Descriptor</label>
    <nameField>
        <label>Descriptor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descriptors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/Dish_has_product__c.object-meta.xml
<CustomObject>
    <label>Dish has product</label>
    <nameField>
        <label>Dish has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DishHasProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dish_has_product__c/fields/New_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Product__c</fullName>
    <label>New Product</label>
    <referenceTo>New_Product__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_Type__c/Meal_Type__c.object-meta.xml
<CustomObject>
    <label>Meal Type</label>
    <nameField>
        <label>MealType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MealTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/Descriptor__c.field-meta.xml
<CustomField>
    <fullName>Descriptor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Descriptor</label>
    <referenceTo>Descriptor__c</referenceTo>
    <relationshipLabel>MealTypes</relationshipLabel>
    <relationshipName>MealTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MealTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_dish__c/Meal_type_has_dish__c.object-meta.xml
<CustomObject>
    <label>Meal type has dish</label>
    <nameField>
        <label>Meal type has dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasDishes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meal_type_has_dish__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>MealTypeHasDishes</relationshipLabel>
    <relationshipName>MealTypeHasDishes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_type_has_dish__c/fields/Grammage__c.field-meta.xml
<CustomField>
    <fullName>Grammage__c</fullName>
    <label>Grammage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_dish__c/fields/Meal_Type__c.field-meta.xml
<CustomField>
    <fullName>Meal_Type__c</fullName>
    <label>Meal Type</label>
    <referenceTo>Meal_Type__c</referenceTo>
    <relationshipLabel>MealTypeHasDishes</relationshipLabel>
    <relationshipName>MealTypeHasDishes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_product__c/Meal_type_has_product__c.object-meta.xml
<CustomObject>
    <label>Meal type has product</label>
    <nameField>
        <label>Meal type has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_type_has_product__c/fields/Grammage__c.field-meta.xml
<CustomField>
    <fullName>Grammage__c</fullName>
    <label>Grammage</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_product__c/fields/Meal_Type__c.field-meta.xml
<CustomField>
    <fullName>Meal_Type__c</fullName>
    <label>Meal Type</label>
    <referenceTo>Meal_Type__c</referenceTo>
    <relationshipLabel>MealTypeHasProducts</relationshipLabel>
    <relationshipName>MealTypeHasProducts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_product__c/fields/New_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Product__c</fullName>
    <label>New Product</label>
    <referenceTo>New_Product__c</referenceTo>
    <relationshipLabel>MealTypeHasProducts</relationshipLabel>
    <relationshipName>MealTypeHasProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/New_Product__c/New_Product__c.object-meta.xml
<CustomObject>
    <label>New Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Product__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <label>Barcode</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Calories__c.field-meta.xml
<CustomField>
    <fullName>Calories__c</fullName>
    <label>Calories</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Carbohydrates__c</fullName>
    <label>Carbohydrates</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Fat__c.field-meta.xml
<CustomField>
    <fullName>Fat__c</fullName>
    <label>Fat</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Ranking__c/Ranking__c.object-meta.xml
<CustomObject>
    <label>Ranking</label>
    <nameField>
        <label>Ranking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ranking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rankings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestGetMenusToFlow.cls
@isTest
public with sharing class TestGetMenusToFlow {
    @TestSetup
    static void makeData(){
        Ranking__c rank = new Ranking__c();
        rank.Start_date__c = Date.today();
        rank.End_date__c = Date.today().addDays(7);
        insert rank;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'fsd', Email='standard@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Test2', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='xdd@xdd.com');
        insert u;
        List<Descriptor__c> descriptors = new List<Descriptor__c>();
        Descriptor__c breakfast = new Descriptor__c();
        breakfast.Name = 'Breakfast';
        descriptors.add(breakfast);
        Descriptor__c second = new Descriptor__c();
        second.Name = 'Second breakfast';
        descriptors.add(second);
        Descriptor__c dinner = new Descriptor__c();
        dinner.Name = 'Dinner';
        descriptors.add(dinner);
        Descriptor__c lunch = new Descriptor__c();
        lunch.Name = 'Lunch';
        descriptors.add(lunch);
        Descriptor__c snack = new Descriptor__c();
        snack.Name = 'Snack';
        descriptors.add(snack);
        insert descriptors;
        List<Meal_type__c> mlts = new List<Meal_type__c>();
        for(Descriptor__c dsc: descriptors){
            Meal_type__c mealType = new Meal_type__c();
            mealType.User__c = u.Id;
            mealType.Date__c = Date.today();
            mealType.Descriptor__c = dsc.Id;
            mlts.add(mealType);
        }
        insert mlts;
        New_product__c newProduct = new New_product__c();
        newProduct.Name = 'Big Mac';
        newProduct.Barcode__c = '1234567890123';
        newProduct.Calories__c = 230;
        newProduct.Carbohydrates__c = 50;
        newProduct.Fat__c = 20;
        newProduct.Protein__c = 30;
        insert newProduct;
        Dish__c dish = new Dish__c();
        dish.Name = 'McDonalds';
        insert dish;
        Dish_has_product__c productInDish = new Dish_has_product__c();
        productInDish.Dish__c = dish.Id;
        productInDish.New_Product__c = newProduct.Id;
        productInDish.Grammage__c = 50;
        insert productInDish;
        Meal_type_has_dish__c mealTypeDish = new Meal_type_has_dish__c();
        mealTypeDish.Dish__c = dish.Id;
        mealTypeDish.Grammage__c = 100;
        mealTypeDish.Meal_Type__c = mlts[0].Id;
        insert mealTypeDish;
        Meal_type_has_product__c product = new Meal_type_has_product__c();
        product.New_Product__c = newProduct.Id;
        product.Meal_Type__c = mlts[0].Id;
        product.Grammage__c = 120;
        insert product;
    }
    @isTest
    static void productsTest(){
        getMenusToFlow.FlowInput fi = new getMenusToFlow.FlowInput();
        List<Meal_type__c> mealTypes = [SELECT Id FROM Meal_type__c WHERE Date__c =: Date.today()];
        fi.mealType = mealTypes;
        Test.startTest();
        List<getMenusToFlow.FlowOutput> results = getMenusToFlow.products(new List<getMenusToFlow.FlowInput>{fi});
        List<ProductTest> products = new List<ProductTest>();
        List<Dish> dishes = new List<Dish>();
        for(getMenusToFlow.FlowOutput fo : results){
            for(ProductTest product : fo.breakfastProducts){
                products.add(product);
            }
            for(Dish dish : fo.breakfastDishes){
                dishes.add(dish);
            }
        }
        Test.stopTest();
        System.assertEquals(1, products.size(), 'Bad amount of products');
        System.assertEquals(1, dishes.size(), 'Bad amount of dishes');
    }
}