Inzynierka/force-app/main/default/objects/Descriptor__c/Descriptor__c.object-meta.xml
<CustomObject>
    <label>Descriptor</label>
    <nameField>
        <label>Descriptor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descriptors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_Type__c/Meal_Type__c.object-meta.xml
<CustomObject>
    <label>Meal Type</label>
    <nameField>
        <label>MealType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MealTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/Descriptor__c.field-meta.xml
<CustomField>
    <fullName>Descriptor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Descriptor</label>
    <referenceTo>Descriptor__c</referenceTo>
    <relationshipLabel>MealTypes</relationshipLabel>
    <relationshipName>MealTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MealTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/scheduleMealType.cls
public class scheduleMealType implements Schedulable{
    public static void execute(SchedulableContext sc){
        List<User> users = [SELECT Id, Name FROM User];
        List<Descriptor__c> dsc = [SELECT Name FROM Descriptor__c];
        List<Meal_Type__c> mlt = new List<Meal_Type__c>();
        for(User usr : users){
            for(Descriptor__c d : dsc){
                Meal_Type__c mealType = new Meal_Type__c();
                mealType.User__c = usr.Id;
                mealType.Descriptor__c = d.Id;
                mealType.Date__c = Date.today().addDays(1);
                mealType.Name = String.valueOf(usr.Name) + String.valueOf(Date.today().addDays(1)) + String.valueOf(d.Name);
                mlt.add(mealType);
            }
        }
        insert mlt;
    }
}