Inzynierka/force-app/main/default/objects/Meal_Type__c/Meal_Type__c.object-meta.xml
<CustomObject>
    <label>Meal Type</label>
    <nameField>
        <label>MealType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MealTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/Total_calories__c.field-meta.xml
<CustomField>
    <fullName>Total_calories__c</fullName>
    <label>Total calories</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_Type__c/fields/Total_carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Total_carbohydrates__c</fullName>
    <label>Total carbohydrates</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meal_Type__c/fields/Total_proteins__c.field-meta.xml
<CustomField>
    <fullName>Total_proteins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total proteins</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Goal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rapid weight loss (~1kg per week)
                    </fullName>
                <label>Rapid weight loss</label>
            </value>
            <value>
                <fullName>Quick weight loss (~0.75kg per week)</fullName>
                <label>Quick weight loss</label>
            </value>
            <value>
                <fullName>Moderate weight loss (~0.5kg per week)
                    </fullName>
                <label>Moderate weight loss</label>
            </value>
            <value>
                <fullName>Slow weight loss (~0.25kg per week)
                    </fullName>
                <label>Slow weight loss</label>
            </value>
            <value>
                <fullName>Keeping weight</fullName>
            </value>
            <value>
                <fullName>Rapid weight gain (~1kg per week)
                    </fullName>
                <label>Rapid weight gain</label>
            </value>
            <value>
                <fullName>Quick weight gain (~0.75kg per week)</fullName>
                <label>Quick weight gain</label>
            </value>
            <value>
                <fullName>Moderate weight gain (~0.5kg per week)
                    </fullName>
                <label>Moderate weight gain</label>
            </value>
            <value>
                <fullName>Slow weight gain (~0.25kg per week)
                    </fullName>
                <label>Slow weight gain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/PAL__c.field-meta.xml
<CustomField>
    <fullName>PAL__c</fullName>
    <label>PAL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lying in bed</fullName>
            </value>
            <value>
                <fullName>Low physical activity</fullName>
            </value>
            <value>
                <fullName>Moderate physical activity</fullName>
            </value>
            <value>
                <fullName>Regular exercise 2-3 times a week</fullName>
            </value>
            <value>
                <fullName>Daily exercises</fullName>
            </value>
            <value>
                <fullName>Professional athlete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Total_Calories__c.field-meta.xml
<CustomField>
    <fullName>Total_Calories__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Calories</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Total_Carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Total_Carbohydrates__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Carbohydrates</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Total_Proteins__c.field-meta.xml
<CustomField>
    <fullName>Total_Proteins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Proteins</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/testGetTotalsFromMenu.cls
@isTest
public with sharing class testGetTotalsFromMenu {
    @TestSetup
    static void makeData(){
        Meal_type__c mlt = new Meal_type__c();
        mlt.Total_calories__c = 1500;
        mlt.Total_carbohydrates__c = 200;
        mlt.Total_fats__c = 20;
        mlt.Total_proteins__c = 30;
        insert mlt;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'fsd', Email='standard@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Test2', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='xdd@xdd.com');
        u.Gender__c = 'Male';
        u.Weight__c = 86.5;
        u.Height__c = 191;
        u.Age__c = 22;
        u.PAL__c = 'Moderate physical activity';
        u.Goal__c = 'Keeping weight';
        insert u;
    }
    @isTest
    static void testData(){
        getTotalsFromMenu.FlowInput fi = new getTotalsFromMenu.FlowInput();
        Meal_type__c mlt = [SELECT Total_calories__c, Total_carbohydrates__c,
        Total_fats__c, Total_proteins__c FROM Meal_type__c LIMIT 1];
        fi.totalCalories = mlt.Total_calories__c;
        fi.totalCarbohydrates = mlt.Total_carbohydrates__c;
        fi.totalFat = mlt.Total_fats__c;
        fi.totalProtein = mlt.Total_proteins__c;
        
        
        Test.startTest();
            Decimal cal = 0;
            List<getTotalsFromMenu.FlowOutput> results = getTotalsFromMenu.getTotals(new List<getTotalsFromMenu.FlowInput>{fi});
            for(getTotalsFromMenu.FlowOutput fo : results){
                for(MenuTotals menu : fo.totals){
                    cal = menu.calories;
                }
            }    
        Test.stopTest();
        
        System.assertEquals(1500, cal, 'Bad calories');
        System.assertEquals(1, results.size(), 'Bad results'); 
    }
    @isTest
    public static void testGetUserInfoToReports(){
        User u = [SELECT Id, Gender__c, Weight__c, Height__c, PAL__c, Goal__c, Total_Calories__c FROM User WHERE UserName = 'xdd@xdd.com'];
        PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId = '0PS7Q000007KgZ8WAK', AssigneeId = u.Id);
        insert psa;
        Double calories = 0;
        Test.startTest();
        System.runAs(u){
                List<Double> macros = MenuTotals.getUserInfoToReports();
                system.debug(macros);
                calories = macros[0];
        }
        Test.stopTest();
        u = [SELECT Id, Gender__c, Weight__c, Height__c, PAL__c, Goal__c, Total_Calories__c FROM User WHERE UserName = 'xdd@xdd.com'];
        system.debug(u);
        System.assertEquals(3297, calories, 'Bad user calories');
    }
}