Inzynierka/force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inzynierka/force-app/main/default/objects/Dish__c/fields/Total_carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Total_carbohydrates__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total carbohydrates</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Total_fats__c.field-meta.xml
<CustomField>
    <fullName>Total_fats__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total fats</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dish_has_product__c/Dish_has_product__c.object-meta.xml
<CustomObject>
    <label>Dish has product</label>
    <nameField>
        <label>Dish has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DishHasProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dish_has_product__c/fields/New_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Product__c</fullName>
    <label>New Product</label>
    <referenceTo>New_Product__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/New_Product__c/New_Product__c.object-meta.xml
<CustomObject>
    <label>New Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Product__c/fields/Calories__c.field-meta.xml
<CustomField>
    <fullName>Calories__c</fullName>
    <label>Calories</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Carbohydrates__c</fullName>
    <label>Carbohydrates</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Fat__c.field-meta.xml
<CustomField>
    <fullName>Fat__c</fullName>
    <label>Fat</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DishHasProductHelper.cls
public with sharing class DishHasProductHelper {
    
    public static void createCalories(List<Dish_has_product__c> newRecords) {
        Map<Id, Decimal> productsDetails = new Map<Id, Decimal>();
        for(Dish_has_product__c dishHasProduct : newRecords) {
            if(productsDetails.containsKey(dishHasProduct.New_Product__c)) {
                Decimal grammageIncrement = productsDetails.get(dishHasProduct.New_Product__c);
                grammageIncrement += dishHasProduct.Grammage__c;
                productsDetails.put(dishHasProduct.New_Product__c, grammageIncrement);
            } else {
                productsDetails.put(dishHasProduct.New_Product__c, dishHasProduct.Grammage__c);
            }
        }
        System.debug(productsDetails);
        List<New_Product__c> productsToCountCalories = [SELECT Id, Calories__c, Carbohydrates__c, Fat__c, Protein__c FROM New_Product__c WHERE Id IN :productsDetails.keySet()];
        Decimal productCalories = 0;
        Decimal productCarbohydrates = 0;
        Decimal productFat = 0;
        Decimal productProtein = 0;
        for(New_Product__c product : productsToCountCalories) {
            Decimal productGrammage = productsDetails.get(product.Id)/100;
            productCalories += product.Calories__c * productGrammage;
            productCarbohydrates += product.Carbohydrates__c * productGrammage;
            productFat += product.Fat__c * productGrammage;
            productProtein += product.Protein__c * productGrammage;
        }
        Dish__c dish = [SELECT Id, Total_calories__c, Total_carbohydrates__c, Total_fats__c, Total_proteins__c FROM Dish__c WHERE Id =: newRecords[0].Dish__c];
        dish.Total_calories__c = productCalories;
        dish.Total_carbohydrates__c = productCarbohydrates;
        dish.Total_fats__c = productFat;
        dish.Total_proteins__c = productProtein;
        update dish;
    }
}