Inzynierka/force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/Dish_has_product__c.object-meta.xml
<CustomObject>
    <label>Dish has product</label>
    <nameField>
        <label>Dish has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DishHasProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dish_has_product__c/fields/New_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Product__c</fullName>
    <label>New Product</label>
    <referenceTo>New_Product__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_dish__c/Meal_type_has_dish__c.object-meta.xml
<CustomObject>
    <label>Meal type has dish</label>
    <nameField>
        <label>Meal type has dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasDishes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meal_type_has_dish__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>MealTypeHasDishes</relationshipLabel>
    <relationshipName>MealTypeHasDishes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_type_has_dish__c/fields/Grammage__c.field-meta.xml
<CustomField>
    <fullName>Grammage__c</fullName>
    <label>Grammage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/New_Product__c.object-meta.xml
<CustomObject>
    <label>New Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Product__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <label>Barcode</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Calories__c.field-meta.xml
<CustomField>
    <fullName>Calories__c</fullName>
    <label>Calories</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Carbohydrates__c.field-meta.xml
<CustomField>
    <fullName>Carbohydrates__c</fullName>
    <label>Carbohydrates</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/fields/Fat__c.field-meta.xml
<CustomField>
    <fullName>Fat__c</fullName>
    <label>Fat</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/New_Product__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/ShowProductsInDishTest.cls
@isTest
public with sharing class ShowProductsInDishTest {
    @TestSetup
    static void makeData(){
        Dish__c dish = new Dish__c();
        Dish__c dishWithoutProd = new Dish__c(Name='No Products');
        insert new List<Dish__c>{dish, dishWithoutProd};
        Meal_type_has_dish__c mealType = new Meal_type_has_dish__c(Dish__c=dish.Id, Grammage__c=10);
        Meal_type_has_dish__c mealTypeWithoutDish = new Meal_type_has_dish__c(Grammage__c=0);
        insert new List<Meal_type_has_dish__c>{mealType, mealTypeWithoutDish};
        New_Product__c product = new New_Product__c(Barcode__c='1234567890123', Calories__c=50, Carbohydrates__c=5, Fat__c=1, Protein__c=2);
        insert product;
        Dish_has_product__c dish_product = new Dish_has_product__c(New_Product__c=product.Id, Grammage__c=100, Dish__c=dish.Id);
        insert dish_product;
    }
    @isTest
    public static void showProductsTestPositive(){
        Meal_type_has_dish__c mealType = [SELECT Id FROM Meal_type_has_dish__c WHERE Grammage__c=10 LIMIT 1];
        Test.startTest();
        List<New_product__c> result = showProductsInDish.showProducts(mealType.Id);
        Test.stopTest();
        System.assert(result.size() > 0, 'Result list size should be > 0');
        System.assertEquals(1, result.size(), 'Result list size should be exactly 1');
    }
    @isTest
    public static void showProductsTestNegative(){

        Meal_type_has_dish__c mealType = [SELECT Id FROM Meal_type_has_dish__c WHERE Grammage__c=0 LIMIT 1];
        Test.startTest();
        List<New_product__c> result = showProductsInDish.showProducts(mealType.Id);
        Test.stopTest();
        System.assert(result.size() < 1, 'Result list size should be less than 1');
        System.assertEquals(0, result.size(), 'Result list size should be exactly 0');
    }
}