Inzynierka/force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/Dish_has_product__c.object-meta.xml
<CustomObject>
    <label>Dish has product</label>
    <nameField>
        <label>Dish has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DishHasProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_has_product__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dish_has_product__c/fields/New_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Product__c</fullName>
    <label>New Product</label>
    <referenceTo>New_Product__c</referenceTo>
    <relationshipLabel>DishHasProducts</relationshipLabel>
    <relationshipName>DishHasProducts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_dish__c/Meal_type_has_dish__c.object-meta.xml
<CustomObject>
    <label>Meal type has dish</label>
    <nameField>
        <label>Meal type has dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasDishes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meal_type_has_dish__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>MealTypeHasDishes</relationshipLabel>
    <relationshipName>MealTypeHasDishes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Meal_type_has_dish__c/fields/Grammage__c.field-meta.xml
<CustomField>
    <fullName>Grammage__c</fullName>
    <label>Grammage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product__c/New_Product__c.object-meta.xml
<CustomObject>
    <label>New Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/showProductsInDish.cls
public with sharing class showProductsInDish {
    @AuraEnabled(cacheable = true)
    public static List<New_product__c> showProducts(Id recordId){
        Id dish = [SELECT Dish__r.Id FROM Meal_type_has_dish__c WHERE Id =: recordId LIMIT 1].Dish__c;
        List<Dish_has_product__c> productsInDish = [SELECT Id, New_Product__c, Grammage__c FROM Dish_has_product__c WHERE Dish__c =: dish];
        List<New_product__c> products = new List<New_Product__c>();
        Set<Id> productsId = new Set<Id>();
        for(Dish_has_product__c dishProduct : productsInDish){
            productsId.add(dishProduct.New_Product__c);
        }
        products = [SELECT Name FROM New_Product__c WHERE Id IN: productsId];
        return products;
    }
}