Inzynierka/force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meal_type_has_dish__c/Meal_type_has_dish__c.object-meta.xml
<CustomObject>
    <label>Meal type has dish</label>
    <nameField>
        <label>Meal type has dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasDishes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meal_type_has_dish__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>MealTypeHasDishes</relationshipLabel>
    <relationshipName>MealTypeHasDishes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meal_type_has_product__c/Meal_type_has_product__c.object-meta.xml
<CustomObject>
    <label>Meal type has product</label>
    <nameField>
        <label>Meal type has product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealTypeHasProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/tests/ListProductControllerTest.cls
@isTest
public with sharing class ListProductControllerTest {
    @TestSetup
    static void makeData(){
        Meal_type_has_product__c mealWithProduct = new Meal_type_has_product__c();
        insert mealWithProduct;
        Meal_type_has_dish__c mealWithDish = new Meal_type_has_dish__c();
        insert mealWithDish;
        Dish__c dish = new Dish__c();
        insert dish;
    }

    @isTest
    public static void deleteSelectedMealTypeProductTest() {
        Meal_type_has_product__c meal = [SELECT Id FROM Meal_type_has_product__c LIMIT 1];
        Test.startTest();
        listProductController.deleteSelectedMealType(meal.Id);
        Test.stopTest();
        
        List<Meal_type_has_product__c> resultMeals = [SELECT Id FROM Meal_type_has_product__c];
        List<Meal_type_has_dish__c> mealWithDish = [SELECT Id FROM Meal_type_has_dish__c];
        System.assert(resultMeals.size() != 1, 'Meal should be deleted');
        System.assertEquals(3, Limits.getDmlStatements(), 'Two DMLs should be done - SELECT and DELETE');
        System.assertEquals(0, resultMeals.size(), 'No records should be found');
        System.assertEquals(1, mealWithDish.size(), 'Meal types with dishes shouldnt be deleted');
    }
    @isTest
    public static void deleteSelectedMealTypeDishTest() {
        Meal_type_has_dish__c meal = [SELECT Id FROM Meal_type_has_dish__c LIMIT 1];
        Test.startTest();
        listProductController.deleteSelectedMealType(meal.Id);
        Test.stopTest();
        
        List<Meal_type_has_dish__c> resultMeals = [SELECT Id FROM Meal_type_has_dish__c];
        List<Meal_type_has_product__c> mealWithProduct = [SELECT Id FROM Meal_type_has_product__c];
        System.assertEquals(3, Limits.getDmlStatements(), '3 DMLs should be done - 2x SELECT and DELETE');
        System.assert(resultMeals.size() != 1, 'Meal should be deleted');
        System.assertEquals(0, resultMeals.size(), 'No records should be found');
        System.assertEquals(1, mealWithProduct.size(), 'Meal types with products shouldnt be deleted');
    }
    @isTest
    public static void deleteSelectedMealTypeNegativeTest() {
        Dish__c dish = [SELECT Id FROM Dish__c LIMIT 1];
        Test.startTest();
        listProductController.deleteSelectedMealType(dish.Id);
        Test.stopTest();
        
        List<Meal_type_has_dish__c> resultMeals = [SELECT Id FROM Meal_type_has_dish__c];
        List<Meal_type_has_product__c> mealWithProduct = [SELECT Id FROM Meal_type_has_product__c];
        System.assert(resultMeals.size() > 0, 'Meal should not be deleted');
        System.assertEquals(3, Limits.getDmlStatements(), '3 DMLs should be done');
        System.assertEquals(1, resultMeals.size(), 'No records should be deleted');
        System.assertEquals(1, mealWithProduct.size(), 'Meal types with products shouldnt be deleted');
    }

}