Inzynierka/force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Burned_calories__c.field-meta.xml
<CustomField>
    <fullName>Burned_calories__c</fullName>
    <description>Burned calories/1h activity</description>
    <label>Burned calories</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/Activity_Log__c.object-meta.xml
<CustomObject>
    <label>Activity Log</label>
    <nameField>
        <label>Activity Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Log__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Activity_Log__c/fields/Activity_points__c.field-meta.xml
<CustomField>
    <fullName>Activity_points__c</fullName>
    <label>Activity points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Burned_calories__c.field-meta.xml
<CustomField>
    <fullName>Burned_calories__c</fullName>
    <label>Burned calories</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_log_has_activity__c/Activity_log_has_activity__c.object-meta.xml
<CustomObject>
    <label>Activity log has activity</label>
    <nameField>
        <label>Activity log has activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity logs has activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_log_has_activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Activity logs has activity</relationshipLabel>
    <relationshipName>Activity_logs_has_activity</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_log_has_activity__c/fields/Activity_Log__c.field-meta.xml
<CustomField>
    <fullName>Activity_Log__c</fullName>
    <label>Activity Log</label>
    <referenceTo>Activity_Log__c</referenceTo>
    <relationshipLabel>Activity logs has activity</relationshipLabel>
    <relationshipName>Activity_logs_has_activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Activity_log_has_activity__c/fields/Activity_points__c.field-meta.xml
<CustomField>
    <fullName>Activity_points__c</fullName>
    <label>Activity points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_log_has_activity__c/fields/Burned_calories__c.field-meta.xml
<CustomField>
    <fullName>Burned_calories__c</fullName>
    <label>Burned calories</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Activity_log_has_activity__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/showActivityLog.cls
global with sharing class showActivityLog {
    public class FlowInput{
        @InvocableVariable public Id activityLog;
    }

    public static List<Activity> getActivities(Id activityLogId)
    {
        List<Activity_log_has_activity__c> activityLogs = [SELECT Id, Activity__r.Name, Burned_calories__c, Time__c, Activity_points__c 
        FROM Activity_log_has_activity__c WHERE Activity_Log__c =: activityLogId];
        List<Activity> activities = new List<Activity>();
        for(Activity_log_has_activity__c act : activityLogs){
            Activity activity = new Activity(act.Id, act.Activity__r.Name, act.Burned_calories__C, act.Time__c, act.Activity_points__c);
            activities.add(activity);
        }
        return activities;
    }
    @InvocableMethod(label='Get Activities')
    public static FlowOutput[] activities(List<FlowInput> params){
        FlowOutput[] results = new List<FlowOutput>();
        Id actId = params[0].activityLog;
        List<Activity> acts = getActivities(actId);
        results.add(new FlowOutput(acts));
        return results;
    }
    public class FlowOutput{
        @InvocableVariable public List<Activity> activities;

        public FlowOutput(List<Activity> activities) {
            this.activities = activities;
        }
    }
}