Inzynierka/force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Burned_calories__c.field-meta.xml
<CustomField>
    <fullName>Burned_calories__c</fullName>
    <description>Burned calories/1h activity</description>
    <label>Burned calories</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/Activity_Log__c.object-meta.xml
<CustomObject>
    <label>Activity Log</label>
    <nameField>
        <label>Activity Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Log__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Burned_calories__c.field-meta.xml
<CustomField>
    <fullName>Burned_calories__c</fullName>
    <label>Burned calories</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log_has_activity__c/Activity_log_has_activity__c.object-meta.xml
<CustomObject>
    <label>Activity log has activity</label>
    <nameField>
        <label>Activity log has activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity logs has activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_log_has_activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Activity logs has activity</relationshipLabel>
    <relationshipName>Activity_logs_has_activity</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_log_has_activity__c/fields/Activity_Log__c.field-meta.xml
<CustomField>
    <fullName>Activity_Log__c</fullName>
    <label>Activity Log</label>
    <referenceTo>Activity_Log__c</referenceTo>
    <relationshipLabel>Activity logs has activity</relationshipLabel>
    <relationshipName>Activity_logs_has_activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_log_has_activity__c/fields/Burned_calories__c.field-meta.xml
<CustomField>
    <fullName>Burned_calories__c</fullName>
    <label>Burned calories</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inzynierka/force-app/main/default/objects/Activity_log_has_activity__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Goal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rapid weight loss (~1kg per week)
                    </fullName>
                <label>Rapid weight loss</label>
            </value>
            <value>
                <fullName>Quick weight loss (~0.75kg per week)</fullName>
                <label>Quick weight loss</label>
            </value>
            <value>
                <fullName>Moderate weight loss (~0.5kg per week)
                    </fullName>
                <label>Moderate weight loss</label>
            </value>
            <value>
                <fullName>Slow weight loss (~0.25kg per week)
                    </fullName>
                <label>Slow weight loss</label>
            </value>
            <value>
                <fullName>Keeping weight</fullName>
            </value>
            <value>
                <fullName>Rapid weight gain (~1kg per week)
                    </fullName>
                <label>Rapid weight gain</label>
            </value>
            <value>
                <fullName>Quick weight gain (~0.75kg per week)</fullName>
                <label>Quick weight gain</label>
            </value>
            <value>
                <fullName>Moderate weight gain (~0.5kg per week)
                    </fullName>
                <label>Moderate weight gain</label>
            </value>
            <value>
                <fullName>Slow weight gain (~0.25kg per week)
                    </fullName>
                <label>Slow weight gain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/PAL__c.field-meta.xml
<CustomField>
    <fullName>PAL__c</fullName>
    <label>PAL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lying in bed</fullName>
            </value>
            <value>
                <fullName>Low physical activity</fullName>
            </value>
            <value>
                <fullName>Moderate physical activity</fullName>
            </value>
            <value>
                <fullName>Regular exercise 2-3 times a week</fullName>
            </value>
            <value>
                <fullName>Daily exercises</fullName>
            </value>
            <value>
                <fullName>Professional athlete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestShowActivityLog.cls
@isTest
public with sharing class TestShowActivityLog {
    @TestSetup
    static void makeData(){
        Activity__c activity = new Activity__c();
        activity.Name = 'Football';
        activity.Burned_calories__c = 500;
        insert activity;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'fsd', Email='standard@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Test2', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='xdd@xdd.com');
        u.Gender__c = 'Male';
        u.Weight__c = 86.5;
        u.Height__c = 181;
        u.PAL__c = 'Moderate physical activity';
        u.Goal__c = 'Keeping weight';
        insert u;
        Activity_log__c act = new Activity_log__c();
        act.Date__c = Date.today();
        act.User__c = u.Id;
        insert act;
        Activity_log_has_activity__c actAct = new Activity_log_has_activity__c();
        actAct.Activity_Log__c = act.Id;
        actAct.Activity__c = activity.Id;
        actAct.Time__c = 30;
        insert actAct;
    }
    @isTest
    static void showActivityTest(){
        showActivityLog.FlowInput aL = new showActivityLog.FlowInput();
        Id actId = [SELECT Id FROM Activity_log__c LIMIT 1].Id;
        aL.activityLog = actId;
        
        
        Test.startTest();
            List<showActivityLog.FlowOutput> results = showActivityLog.activities(new List<showActivityLog.FlowInput>{aL});
            List<Activity> acts = new List<Activity>();
            for(showActivityLog.FlowOutput fo : results){
                for(Activity activ : fo.activities){
                    acts.add(activ);
                }
            }    
        Test.stopTest();
        System.assertEquals(1, acts.size(), 'Bad size');
        System.assertEquals(6, acts[0].activityPoints);
    }
}