force-app/main/default/objects/Ranking_has_user__c/Ranking_has_user__c.object-meta.xml
<CustomObject>
    <label>Ranking has user</label>
    <nameField>
        <label>Ranking has user Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ranking has users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ranking_has_user__c/fields/Activity_points__c.field-meta.xml
<CustomField>
    <fullName>Activity_points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Activity points</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ranking_has_user__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Position</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ranking_has_user__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ranking_has_users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Activity_points__c.field-meta.xml
<CustomField>
    <fullName>Activity_points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Activity points</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/getRanking.cls
global with sharing class getRanking {
    public class FlowInput{
        @InvocableVariable public List<Ranking_has_user__c> rankingHasUser;
    }
    public static List<Ranking> getRanking(Set<Id> ids){
        List<Ranking_has_user__c> rankings = [SELECT Position__c, Activity_points__c, User__r.Name FROM Ranking_has_user__c WHERE Id IN: ids ORDER BY Position__c ASC];
        List<Ranking> finalRanking = new List<Ranking>();
        for(Ranking_has_user__c rnk : rankings){
            Ranking rank = new Ranking(rnk.Id, rnk.Position__c, rnk.Activity_points__c, rnk.User__r.Name);
            finalRanking.add(rank);
        }
        return finalRanking;
    }
    @InvocableMethod(label='Get ranking')
    public static FlowOutput[] users(List<FlowInput> params){
        FlowOutput[] results = new List<FlowOutput>();
        Set<Id> rankingsId = new Set<Id>();
        for(FlowInput input : params){
            for(Ranking_has_user__c rank : input.rankingHasUser){
                rankingsId.add(rank.Id);
            }
        }
        List<Ranking> ranking = getRanking(rankingsId);
        results.add(new FlowOutput(ranking));
        return results;
    }
    public class FlowOutput{
        @InvocableVariable public List<Ranking> rankings;

        public FlowOutput(List<Ranking> rankings){
            this.rankings = rankings;
        }
    }
}